# Generated by Django 4.1.2 on 2022-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctor_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(default=100),
        ),
    ]
